[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
seeds = false
skip-lint = false

[programs.localnet]
game = "BDS42gR1XMtdDGPJqUkCnsNvSRvrte1onM9y8JHQbcgJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
